# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 600)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.replays_folder_line_edit = QtWidgets.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.replays_folder_line_edit.setFont(font)
        self.replays_folder_line_edit.setObjectName("replays_folder_line_edit")
        self.gridLayout.addWidget(self.replays_folder_line_edit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.stash_folder_line_edit = QtWidgets.QLineEdit(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.stash_folder_line_edit.setFont(font)
        self.stash_folder_line_edit.setObjectName("stash_folder_line_edit")
        self.gridLayout.addWidget(self.stash_folder_line_edit, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.replays_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.replays_group_box.setObjectName("replays_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.replays_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.replays_group_box)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.replays_table_widget = QtWidgets.QTableWidget(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.replays_table_widget.setFont(font)
        self.replays_table_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.replays_table_widget.setObjectName("replays_table_widget")
        self.replays_table_widget.setColumnCount(0)
        self.replays_table_widget.setRowCount(0)
        self.replays_table_widget.horizontalHeader().setHighlightSections(False)
        self.replays_table_widget.horizontalHeader().setStretchLastSection(True)
        self.replays_table_widget.verticalHeader().setVisible(False)
        self.replays_table_widget.verticalHeader().setDefaultSectionSize(40)
        self.verticalLayout_3.addWidget(self.replays_table_widget)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.replays_group_box)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stash_button = QtWidgets.QPushButton(self.frame_2)
        self.stash_button.setObjectName("stash_button")
        self.horizontalLayout.addWidget(self.stash_button)
        self.unstash_button = QtWidgets.QPushButton(self.frame_2)
        self.unstash_button.setObjectName("unstash_button")
        self.horizontalLayout.addWidget(self.unstash_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.replays_table_refresh_button = QtWidgets.QPushButton(self.frame_2)
        self.replays_table_refresh_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.replays_table_refresh_button.setObjectName("replays_table_refresh_button")
        self.horizontalLayout.addWidget(self.replays_table_refresh_button)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.replays_group_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Replay Organiser"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Folders"))
        self.label.setText(_translate("MainWindow", "Replays:"))
        self.label_2.setText(_translate("MainWindow", "Stash:"))
        self.replays_group_box.setTitle(_translate("MainWindow", "Replays"))
        self.stash_button.setText(_translate("MainWindow", "Stash"))
        self.unstash_button.setText(_translate("MainWindow", "Unstash"))
        self.replays_table_refresh_button.setText(_translate("MainWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
